version: 0.1

phases:
  build:
    command:
      - echo Entered the build phase
      - mvn clean package
    post_build:
      command:
        - echo Build Completed Successfully
artifacts:
  files:
    - 'target/helloSpringBootApplication.jar'
  discard-paths: yes